server:
  port: 9000 
spring:
  application:
    name: first-cloud-invoker
eureka: 
  instance:
    hostname: localhost 
  client:
    serviceUrl:
      defaultZone : http://slave1:8761/eureka/,http://slave1:8762/eureka/